// Self-contained fallback mock data when Docker/Postgres is not running on host machine
export const mockDb = {
  users: [
    {
      id: 'u1',
      name: 'Dr. Ahmed Hassan',
      email: 'admin@commercehub.edu',
      studentId: null,
      role: 'super_admin',
      passwordChanged: true,
    },
    {
      id: 'u2',
      name: 'Sara Ali',
      email: 'assistant@commercehub.edu',
      studentId: null,
      role: 'admin',
      passwordChanged: true,
    },
    {
      id: 'u3',
      name: 'Mohamed Ibrahim',
      email: 'student1@commercehub.edu',
      studentId: '10000001',
      role: 'student',
      passwordChanged: true,
    },
    {
      id: 'u4',
      name: 'Fatima Al-Zahra',
      email: 'student2@commercehub.edu',
      studentId: '10000002',
      role: 'student',
      passwordChanged: true,
    },
  ],

  courses: [
    {
      id: 'c1',
      title: 'Introduction to Statistics',
      title_ar: 'مقدمة في الإحصاء',
      description: 'Fundamental concepts of statistics, probability, and business data analysis.',
      description_ar: 'المفاهيم الأساسية في الإحصاء والاحتمالات وتحليل البيانات لطلاب كلية التجارة.',
      enrolled_students_count: 5,
      lectures_count: 2,
      exams_count: 1,
    },
    {
      id: 'c2',
      title: 'Financial Accounting',
      title_ar: 'المحاسبة المالية',
      description: 'Principles of financial accounting, balance sheets, and financial statements.',
      description_ar: 'مبادئ المحاسبة المالية والقوائم المالية وإعداد الميزانية العمومية.',
      enrolled_students_count: 5,
      lectures_count: 1,
      exams_count: 1,
    },
  ],

  lectures: [
    {
      id: 'l1',
      course_id: 'c1',
      title: 'Chapter 1: Descriptive Statistics',
      title_ar: 'الفصل الأول: الإحصاء الوصفي ومقاييس النزعة المركزية',
      sort_order: 1,
      created_at: new Date(Date.now() - 3 * 24 * 3600 * 1000).toISOString(),
      viewed: true,
    },
    {
      id: 'l2',
      course_id: 'c1',
      title: 'Chapter 2: Probability Distributions',
      title_ar: 'الفصل الثاني: التوزيعات الاحتمالية للمتغيرات العشوائية',
      sort_order: 2,
      created_at: new Date(Date.now() - 1 * 24 * 3600 * 1000).toISOString(),
      viewed: false,
    },
    {
      id: 'l3',
      course_id: 'c2',
      title: 'Unit 1: The Accounting Equation',
      title_ar: 'الوحدة الأولى: معادلة الميزانية والمفاهيم المحاسبية',
      sort_order: 1,
      created_at: new Date(Date.now() - 2 * 24 * 3600 * 1000).toISOString(),
      viewed: false,
    },
  ],

  exams: [
    {
      id: 'e1',
      course_id: 'c1',
      course_title: 'Introduction to Statistics',
      course_title_ar: 'مقدمة في الإحصاء',
      title: 'Midterm Exam - Business Statistics',
      title_ar: 'امتحان منتصف الفصل - إحصاء الأعمال',
      window_start: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
      window_end: new Date(Date.now() + 5 * 24 * 3600 * 1000).toISOString(),
      duration_minutes: 45,
      total_marks: 20.0,
      pass_mark: 10.0, // Strictly 50%
      max_attempts: 2,
      my_attempts_count: 0,
      my_best_score: null,
      score_policy: 'best',
      published: true,
      question_count: 4,
      window_status: 'active',
      has_active_attempt: false,
    },
    {
      id: 'e2',
      course_id: 'c2',
      course_title: 'Financial Accounting',
      course_title_ar: 'المحاسبة المالية',
      title: 'Quiz 1 - Accounting Principles',
      title_ar: 'اختبار قصير 1 - مبادئ المحاسبة',
      window_start: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
      window_end: new Date(Date.now() + 3 * 24 * 3600 * 1000).toISOString(),
      duration_minutes: 30,
      total_marks: 10.0,
      pass_mark: 5.0, // Strictly 50%
      max_attempts: 1,
      my_attempts_count: 0,
      my_best_score: null,
      score_policy: 'best',
      published: true,
      question_count: 2,
      window_status: 'active',
      has_active_attempt: false,
    },
  ],

  questions: {
    e1: [
      {
        id: 'q1',
        type: 'mcq',
        text: 'What measure of central tendency is most affected by extreme outliers?',
        text_ar: 'أي مقاييس النزعة المركزية يتأثر بشدة بالقيم المتطرفة؟',
        points: 5.0,
        correct_key: 'B',
        options: [
          { key: 'A', text: 'Median', text_ar: 'الوسيط' },
          { key: 'B', text: 'Mean', text_ar: 'الوسط الحسابي' },
          { key: 'C', text: 'Mode', text_ar: 'المنوال' },
          { key: 'D', text: 'Standard Deviation', text_ar: 'الانحراف المعياري' },
        ],
      },
      {
        id: 'q2',
        type: 'true_false',
        text: 'The sum of probabilities in a discrete probability distribution always equals 1.',
        text_ar: 'مجموع الاحتمالات في التوزيع الاحتمالي المنفصل يساوي دائماً 1.',
        points: 5.0,
        correct_key: 'A',
        options: [
          { key: 'A', text: 'True', text_ar: 'صواب' },
          { key: 'B', text: 'False', text_ar: 'خطأ' },
        ],
      },
      {
        id: 'q3',
        type: 'mcq',
        text: 'If the correlation coefficient r = -0.92, this indicates:',
        text_ar: 'إذا كان معامل الارتباط r = -0.92، فهذا يشير إلى:',
        points: 5.0,
        correct_key: 'C',
        options: [
          { key: 'A', text: 'No linear relationship', text_ar: 'لا توجد علاقة خطية' },
          { key: 'B', text: 'Weak positive relationship', text_ar: 'علاقة طردية ضعيفة' },
          { key: 'C', text: 'Strong negative relationship', text_ar: 'علاقة عكسية قوية' },
          { key: 'D', text: 'Non-linear correlation', text_ar: 'علاقة غير خطية' },
        ],
      },
      {
        id: 'q4',
        type: 'true_false',
        text: 'Standard deviation can have a negative value.',
        text_ar: 'يمكن أن يكون للانحراف المعياري قيمة سالبة.',
        points: 5.0,
        correct_key: 'B',
        options: [
          { key: 'A', text: 'True', text_ar: 'صواب' },
          { key: 'B', text: 'False', text_ar: 'خطأ' },
        ],
      },
    ],
    e2: [
      {
        id: 'q5',
        type: 'mcq',
        text: 'Assets are equal to Liabilities plus:',
        text_ar: 'الأصول تساوي الالتزامات مضافاً إليها:',
        points: 5.0,
        correct_key: 'A',
        options: [
          { key: 'A', text: "Owner's Equity", text_ar: 'حقوق الملكية' },
          { key: 'B', text: 'Revenue', text_ar: 'الإيرادات' },
          { key: 'C', text: 'Expenses', text_ar: 'المصروفات' },
          { key: 'D', text: 'Net Profit', text_ar: 'صافي الربح' },
        ],
      },
      {
        id: 'q6',
        type: 'true_false',
        text: 'The balance sheet reports the financial position of a firm at a specific point in time.',
        text_ar: 'توضح الميزانية العمومية المركز المالي للمنشأة في لحظة زمنية محددة.',
        points: 5.0,
        correct_key: 'A',
        options: [
          { key: 'A', text: 'True', text_ar: 'صواب' },
          { key: 'B', text: 'False', text_ar: 'خطأ' },
        ],
      },
    ],
  },

  results: [
    {
      attempt_id: 'att1',
      student_id: 'u3',
      student_name: 'Mohamed Ibrahim',
      student_number: '10000001',
      student_email: 'student1@commercehub.edu',
      exam_id: 'e1',
      exam_title: 'Midterm Exam - Business Statistics',
      exam_title_ar: 'امتحان منتصف الفصل - إحصاء الأعمال',
      attempt_number: 1,
      score: 15.0,
      total_marks: 20.0,
      pass_mark: 10.0,
      passed: true,
      submitted_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    },
    {
      attempt_id: 'att2',
      student_id: 'u4',
      student_name: 'Fatima Al-Zahra',
      student_number: '10000002',
      student_email: 'student2@commercehub.edu',
      exam_id: 'e1',
      exam_title: 'Midterm Exam - Business Statistics',
      exam_title_ar: 'امتحان منتصف الفصل - إحصاء الأعمال',
      attempt_number: 1,
      score: 5.0,
      total_marks: 20.0,
      pass_mark: 10.0,
      passed: false,
      submitted_at: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    },
  ],

  notifications: [
    {
      id: 'n1',
      title: 'Welcome to CommerceHub Platform',
      title_ar: 'مرحباً بكم في منصة كلية التجارة التعليمية',
      body: 'Welcome all students to the faculty semester learning system.',
      body_ar: 'أهلاً بجميع الطلاب في منصة الفصل الدراسي بكلية التجارة.',
      read: false,
      created_at: new Date().toISOString(),
    },
    {
      id: 'n2',
      title: 'Upcoming Exam: Midterm Exam - Business Statistics',
      title_ar: 'امتحان قادم: إحصاء الأعمال',
      body: 'The exam window is now active. You have 2 attempts.',
      body_ar: 'فترة الامتحان متاحة الآن. لديك محاولتان.',
      read: false,
      created_at: new Date(Date.now() - 3600 * 1000).toISOString(),
    },
  ],

  overview: {
    totalStudents: 142,
    totalCourses: 6,
    totalExams: 8,
    totalAttempts: 215,
    passRate: 78,
    averageScore: 14.8,
    totalPdfViews: 840,
  },

  gradeDistribution: [
    { bucket: '0-49% (Fail)', student_count: 14 },
    { bucket: '50-64% (Pass)', student_count: 28 },
    { bucket: '65-74% (Good)', student_count: 45 },
    { bucket: '75-84% (Very Good)', student_count: 52 },
    { bucket: '85-100% (Excellent)', student_count: 36 },
  ],

  passFail: [
    { name: 'Passed (>=50%)', name_ar: 'ناجح (>=50%)', count: 161, color: '#10b981' },
    { name: 'Failed (<50%)', name_ar: 'راسب (<50%)', count: 32, color: '#ef4444' },
  ],

  engagement: [
    { lecture_title: 'Descriptive Stats', lecture_title_ar: 'الإحصاء الوصفي', view_count: 245, unique_students_viewed: 112 },
    { lecture_title: 'Probability Distributions', lecture_title_ar: 'التوزيعات الاحتمالية', view_count: 182, unique_students_viewed: 94 },
    { lecture_title: 'The Accounting Equation', lecture_title_ar: 'معادلة الميزانية', view_count: 290, unique_students_viewed: 128 },
  ],

  atRisk: [
    {
      id: 'u9',
      student_id: '10000088',
      name: 'Tarek Mahmoud',
      email: 'tarek@commercehub.edu',
      average_score: 8.2,
      failed_exams_count: 2,
    },
  ],
};
